### ISSUE TITLE
hack is not working

### ISSUE THREAD

**Issue by eimonpakzad** [DavidsCoding/survivio-plus#14]
![Screenshot 2019-12-23 at 10 16 03 AM](https://user-images.githubusercontent.com/35317687/71365527-47884f80-256d-11ea-8ea7-871cbe63fbcb.png)

**Comment by DavidsCoding** [comment]
click details
click allow in incognito
try in incognito

**Comment by eimonpakzad** [comment]
it does not work

**Comment by DavidsCoding** [comment]
check my recent video
